version: '3.9'

services:
  web:
    build: .
    command:
      - bash
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/local_library
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    networks:
      - djangoNet
  db:
    image: mysql:8
    ports:
      - '3308:3306'
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: 'localhost'
      TZ: 'Asia/Dhaka'
    volumes:
      - ./db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - djangoNet
    # command: mysqld --character-set-server=utfmb4 --collation-server=utfmb4_unicode_ci

  # migration:
  #   # build: .
  #   command: 'python manage.py migrate'
  #   volumes:
  #     - .:/local_library
  #   depends_on:
  #     - 'db'
  #     - 'make-migrations'
  #   networks:
  #     - djangoNet

  # make-migrations:
  #   build: .
  #   command: 'python manage.py makemigrations'
  #   volumes:
  #     - .:/local_library
  #   depends_on:
  #     - 'db'
  #   networks:
  #     - djangoNet
networks:
  djangoNet:
